# Builds a standalone harness from src/kit.cpp and src/membrane.hpp by
# EXTRACTING the real blocks. Nothing here is retyped: if a block cannot be
# found the generator fails loudly rather than silently testing a stale copy.
#
# What it is for. Kit's stereo mode taps the head at TWO points, and where those
# two points sit is a pair of tuned numbers (Drum::micR / micAng) that no amount
# of listening tells you the truth about: whether the two channels are level with
# each other, how much they actually differ, and what a downstream mono sum does
# to the tone are all measurements. This runs the real engine over the real
# presets and reports them.
#
#   cd /tmp && python3 <repo>/tools/kit-stereo-harness.py
#   g++ -std=c++11 -O1 -I<repo>/src -o h h.cpp
#   ./h            # per preset: balance, correlation, mono-sum loss
#   ./h sweep      # the same, sweeping the strike round the head
#   ./h grid       # search mic placements -- how the shipped pair was chosen
import re, sys, os
HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = open(os.path.join(HERE, '..', 'src', 'kit.cpp')).read()
OUT  = os.getcwd()

def grab(pat, label, flags=re.S):
    m = re.search(pat, SRC, flags)
    if not m: sys.exit("EXTRACT FAILED: " + label)
    return m.group(0)

def between(start, end, label):
    a = SRC.find(start)
    if a < 0: sys.exit("EXTRACT FAILED (start): " + label)
    b = SRC.find(end, a)
    if b < 0: sys.exit("EXTRACT FAILED (end): " + label)
    return SRC[a:b + len(end)]

presetS  = grab(r'struct KitPreset \{.*?\n\};', 'struct KitPreset')
presets  = grab(r'static const KitPreset KIT_PRESETS\[\] = \{.*?\n\};', 'KIT_PRESETS')
npreset  = grab(r'static const int KIT_NPRESET = [^\n]*', 'KIT_NPRESET')
paramE   = grab(r'\tenum ParamId \{.*?PARAMS_LEN\n\t\};', 'enum ParamId')
inputE   = grab(r'\tenum InputId \{.*?INPUTS_LEN\n\t\};', 'enum InputId')
# 2026-09: Kit became eight instruments. The knobs are a view onto inst[edit]
# (mirrored into inst[edit].v every sample), pv() became pvc(c, ...), and the
# control-rate mapping is a function of the instrument index. All lifted whole.
instS    = grab(r'\tstruct Inst \{.*?\n\t\};', 'struct Inst')
kitN     = grab(r'static const int KIT_N = \d+;', 'KIT_N')
pv       = grab(r'\tinline float pvc\(int c, int p, int in.*?\n\t\}', 'pvc()')
xinS     = grab(r'\tstatic int pkCol\(int in\) \{.*?\n\t\}', 'pkCol()') + '\n' + \
           grab(r'\tbool xin\(int in, int c, float& out\) \{.*?\n\t\}', 'xin()')
pushP    = grab(r'\tvoid pushSlotToParams\(\) \{.*?\n\t\}', 'pushSlotToParams()')
presetToSlotS = grab(r'\tvoid presetToSlot\(int s, const KitPreset& p\) \{.*?\n\t\}', 'presetToSlot()')
loadP    = grab(r'\tvoid loadPreset\(int i\) \{.*?\n\t\}', 'loadPreset()')
ctlblk   = grab(r'\tvoid control\(int c\) \{.*?\n\t\}', 'control(int c)')
# 2026-09: the hi-hat engine strikes first, the membrane in the else
strikeL  = grab(r'\t\t\t\tif \(I\.engine == Inst::HAT\) I\.hat\.strike\([^\n]*\n\t\t\t\telse drum\.strike\(0\.4f \+ vel\[c\] \* 9\.f, hard, I\.v\[WEIGHT_PARAM\]\);',
                'drum.strike()')

# The display's geometry and its mouse handling, for the `mouse` mode. These are
# the functions that map between the screen and the head, and a mistake in any
# of them is a mic that will not be grabbed or that jumps when you do.
geom = []
for pat, label in (
        (r'\tfloat headRad\(\) const \{[^\n]*\}', 'headRad()'),
        (r'\tfloat headCx\(\)  const \{[^\n]*\}', 'headCx()'),
        (r'\tfloat sizeScale\(\) const \{.*?\n\t\}', 'sizeScale()'),
        (r'\tfloat shellDepth\(float rad\) const \{[^\n]*\}', 'shellDepth()'),
        (r'\tfloat head3Rad\(\) const \{.*?\n\t\}', 'head3Rad()'),
        (r'\tfloat head3Cy\(\) const \{.*?\n\t\}', 'head3Cy()'),
        (r'\tfloat head3Cx\(\) const \{[^\n]*\}', 'head3Cx()'),
        (r'\tvoid headFrame\(float& cx, float& cy, float& rad, float& sq\) const \{.*?\n\t\}', 'headFrame()'),
        (r'\tVec micPos\(int c\) const \{.*?\n\t\}', 'micPos()'),
        (r'\tint micAt\(Vec p\) const \{.*?\n\t\}', 'micAt()'),
        (r'\tvoid placeMic\(int c, Vec p\) \{.*?\n\t\}', 'placeMic()'),
        (r'\tconst Kit::Inst\* cur\(\) const \{[^\n]*\}', 'cur()'),
        (r'\tsfs::Drum& md\(\) const \{[^\n]*\}', 'md()'),
        (r'\tfloat stripH\(\) const \{[^\n]*\}', 'stripH()'),
        (r'\tfloat mainH\(\)  const \{[^\n]*\}', 'mainH()')):
    geom.append(grab(pat, label))
geom = '\n'.join(geom)
tiltC = grab(r'\tstatic constexpr float TILT = [0-9.]+f;', 'TILT')
shellC = grab(r'\tstatic constexpr float SHELL = [0-9.]+f;', 'SHELL')
if 'headFrame' not in geom: sys.exit("EXTRACT FAILED: headFrame vanished")

for tag, blk in (('ctl', ctlblk), ('strike', strikeL)):
    if 'drum.' not in blk:
        sys.exit("EXTRACT FAILED: %s came back empty of the engine" % tag)

H = r'''
// GENERATED by tools/kit-stereo-harness.py -- every block below is lifted
// verbatim from src/kit.cpp. The engine itself is src/membrane.hpp, included.
#include <cmath>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <algorithm>
static float clamp(float v, float lo, float hi){ return v<lo?lo:(v>hi?hi:v); }
#include "membrane.hpp"
#include "kit-hat.hpp"
#include "polykit-messages.hpp"

// ── the Rack shims ──────────────────────────────────────────────────────────
// Just enough of Module for the extracted blocks to compile unaltered.
struct P { float v = 0.f;
           float getValue() const { return v; }
           void setValue(float x) { v = x; } };
struct I { bool c = false; float v = 0.f;
           bool isConnected() const { return c; }
           float getVoltage() const { return v; }
           float getPolyVoltage(int) const { return v; } };
namespace dsp { struct SchmittTrigger { bool process(float, float, float) { return false; } }; static const float FREQ_C4 = 261.6256f; }
__KITN__

__PRESETS__

struct Kit {
__PARAMS__
__INPUTS__
	P params[PARAMS_LEN];
	I inputs[INPUTS_LEN];
__INST__
	Inst inst[KIT_N];
	int edit = 0;
	const PolyKitMessage* xp = nullptr;
__XIN__
	int   headView = 1;
	bool  stereo = false;

__PV__
__PUSH__
__PRESET__
__LOADPRESET__
__CTL__
	// What process() does before control(): the knobs ARE the edit slot.
	void mirror() {
		for (int p = 0; p < PARAMS_LEN; p++)
			if (p != STRIKE_PARAM) inst[edit].v[p] = params[p].getValue();
		inst[edit].quiet = false;
	}
	void control() { mirror(); control(edit); }
	void hit(float velIn) {
		mirror();
		int c = edit;
		Inst& I = inst[c];
		sfs::Drum& drum = I.drum;
		float vel[KIT_N]; vel[c] = velIn;
		float hard = pvc(c, EXCITE_PARAM, EXCITE_INPUT);
__STRIKE__
	}
	// Defaults, taken from the configParam calls so an unloaded Kit is the
	// module you actually get when you place one.
	Kit() {
		params[SIZE_PARAM].v = 0.45f;   params[TENSION_PARAM].v = 0.5f;
		params[STIFF_PARAM].v = 0.f;    params[AIR_PARAM].v = 0.f;
		params[DECAY_PARAM].v = 0.5f;   params[TONE_PARAM].v = 0.5f;
		params[COUPLE_PARAM].v = 0.4f;  params[RESO_PARAM].v = 1.1f;
		params[EXCITE_PARAM].v = 0.7f;  params[WEIGHT_PARAM].v = 1.f;
		params[BEND_PARAM].v = 0.25f;   params[STRIKEY_PARAM].v = 0.42f;
		params[SNARETHR_PARAM].v = 0.3f; params[LEVEL_PARAM].v = 1.f;
		for (int s = 0; s < KIT_N; s++)
			for (int p = 0; p < PARAMS_LEN; p++) inst[s].v[p] = params[p].v;
	}
};

// ── the display, enough of it to push a mouse around ────────────────────────
// Rack's own units: an SVG user unit is 1/75 inch, so a millimetre is 75/25.4
// pixels. Vec and box.size are the widget's, and the geometry below is lifted
// out of KitWidget's display verbatim.
static inline float mm2px(float mm) { return mm * (75.f / 25.4f); }
struct Vec { float x = 0.f, y = 0.f; Vec() {} Vec(float a, float b) : x(a), y(b) {} };
struct Kit;
struct Disp {
	Kit* module = nullptr;
	struct { Vec size; } box;
	int micDrag = -1, micHover = -1;
	const Kit::Inst* S = nullptr;
__TILT__
__SHELL__
__GEOM__
};

// ── measuring ───────────────────────────────────────────────────────────────
static const float SR = 48000.f;
struct Stat { double l = 0, r = 0, lr = 0, m = 0, mono = 0; int n = 0; };

// One strike, held for `sec`, measured. `stereo` picks the engine's own path;
// the mono pass is run separately so the sum can be compared against what Kit
// would have produced with stereo off.
static Stat measure(Kit& k, float sec, bool wires) {
	k.inst[0].drum.sr = SR;
	k.inst[0].drum.clear();
	k.params[Kit::SNARE_PARAM].v = wires ? 0.7f : 0.f;
	k.control();
	k.hit(0.7f);
	// The same drum again, in mono, from the same state.
	Kit mk = k;
	mk.inst[0].drum.clear(); mk.control(); mk.hit(0.7f);

	Stat s;
	int N = (int)(sec * SR);
	for (int i = 0; i < N; i++) {
		float h[2], w[2], hm[1], wm[1];
		k.inst[0].drum.process(h, w, true);
		mk.inst[0].drum.process(hm, wm, false);
		double L = h[0] + w[0], R = h[1] + w[1], M = hm[0] + wm[0];
		s.l += L * L; s.r += R * R; s.lr += L * R;
		s.m += M * M;
		double sum = 0.5 * (L + R);
		s.mono += sum * sum;
		s.n++;
	}
	return s;
}
static double db(double a, double b) { return 20.0 * std::log10((a + 1e-30) / (b + 1e-30)); }

// Four numbers, and they answer four different questions. L/R is where the
// image sits. corr and side/mid are how wide it is (side/mid is the one to
// read: correlation on a signal that is four fifths one common component is
// always high, and says less than it looks like it does). level is whether
// switching stereo on changes the loudness. sum is what a downstream mono
// mixer does to the TONE, with the level difference taken out of it.
static void report(const char* name, const Stat& s) {
	double L = std::sqrt(s.l / s.n), R = std::sqrt(s.r / s.n);
	double M = std::sqrt(s.m / s.n), SUM = std::sqrt(s.mono / s.n);
	double corr = s.lr / (std::sqrt(s.l * s.r) + 1e-30);
	double side = (1 - corr) / (1 + corr + 1e-30);
	printf("  %-13s L/R %+5.2f dB  corr %+6.3f  side %5.1f dB  level %+5.2f dB  sum %+5.2f dB\n",
	       name, db(L, R), corr, 10 * std::log10(side + 1e-9),
	       db(std::sqrt(0.5 * (s.l + s.r) / s.n), M),
	       db(SUM, std::sqrt(0.5 * (s.l + s.r) / s.n)));
}

int main(int argc, char** argv) {
	const char* mode = argc > 1 ? argv[1] : "presets";

	if (!strcmp(mode, "presets")) {
		printf("Every instrument, struck once at its own strike position.\n");
		printf("corr +1 = the two channels are the same signal (no stereo at all),\n");
		printf("0 = unrelated. mono sum vs mono mode is what a downstream summing\n");
		printf("mixer does to the tone.\n\n");
		for (int i = 0; i < KIT_NPRESET; i++) {
			if (KIT_PRESETS[i].engine) continue;   // the hi-hat: tools/kit-hat-check.cpp
			Kit k; k.loadPreset(i);
			report(KIT_PRESETS[i].name, measure(k, 1.0f, KIT_PRESETS[i].snare > 0.f));
		}
	} else if (!strcmp(mode, "sweep")) {
		printf("The default drum, struck round the head. Angle is inaudible in\n");
		printf("mono -- a disc is rotationally symmetric -- so this table is the\n");
		printf("whole of what the second tap buys.\n\n");
		for (int a = 0; a < 12; a++) {
			float th = (float)a / 12.f * 2.f * (float)M_PI;
			Kit k;
			k.params[Kit::STRIKEX_PARAM].v = 0.62f * std::cos(th);
			k.params[Kit::STRIKEY_PARAM].v = 0.62f * std::sin(th);
			char nm[32]; snprintf(nm, sizeof nm, "%3.0f deg", th * 180.f / (float)M_PI);
			report(nm, measure(k, 0.7f, false));
		}
		printf("\n  centre    (the one place the two taps must agree)\n");
		Kit k; k.params[Kit::STRIKEX_PARAM].v = 0.f; k.params[Kit::STRIKEY_PARAM].v = 0.f;
		report("r = 0", measure(k, 0.7f, false));
	} else if (!strcmp(mode, "modes")) {
		// Where the energy actually is, by angular order. m = 0 modes are
		// MONOPOLES: they move the whole head one way, they have no angular
		// shape at all, and so they read identically at every tap on the head.
		// No mic placement can ever decorrelate them. Whatever fraction of the
		// sound they are is the fraction that must stay in the middle, so this
		// is the ceiling on how wide the drum can be.
		printf("energy by angular order m, at the default tap radius\n\n");
		for (int i = 0; i < KIT_NPRESET; i++) {
			if (KIT_PRESETS[i].engine) continue;   // the hi-hat: tools/kit-hat-check.cpp
			Kit k; k.loadPreset(i);
			k.inst[0].drum.sr = SR; k.inst[0].drum.clear(); k.control(); k.hit(0.7f);
			double e[4] = {0,0,0,0};
			const sfs::MembraneShapes& sh = sfs::membraneShapes();
			for (int n = 0; n < (int)(0.6f * SR); n++) {
				float h[2], w[2]; k.inst[0].drum.process(h, w, true);
				for (int q = 0; q < sfs::Drum::NM; q++) {
					int m = sfs::MEMBRANE_MODES[q].m;
					double v = k.inst[0].drum.lo[q].value() * sh.at(q, 0.55f);
					e[m == 0 ? 0 : m == 1 ? 1 : m < 4 ? 2 : 3] += v * v;
				}
			}
			double t = e[0] + e[1] + e[2] + e[3] + 1e-30;
			printf("  %-13s m=0 %4.0f%%   m=1 %4.0f%%   m=2,3 %4.0f%%   m>=4 %4.0f%%\n",
			       KIT_PRESETS[i].name, 100*e[0]/t, 100*e[1]/t, 100*e[2]/t, 100*e[3]/t);
		}
	} else if (!strcmp(mode, "radius")) {
		// A tap's radius decides how much of the monopole it hears. J_0 only
		// vanishes at the rim, so the fundamental can be leaned away from but
		// never escaped -- which is the whole shape of the trade here: out
		// toward the hoop is wider and thinner, in toward the middle is fuller
		// and narrower. Both taps at the SAME radius, so all of the difference
		// between them is angular and the channels stay level with each other.
		printf(" rad |  m=0   m=1  m>=2 | corr  side/mid |  level vs mono\n");
		for (int i = 0; i < 9; i++) {
			float r = 0.30f + 0.07f * i;
			double cs = 0, sm = 0, lv = 0; int n = 0;
			double e[3] = {0,0,0};
			for (int p = 0; p < KIT_NPRESET; p++) for (int a = 0; a < 4; a++) {
				if (KIT_PRESETS[p].engine) continue;   // the hi-hat: tools/kit-hat-check.cpp
				Kit k; k.loadPreset(p);
				float th = (float)a / 4.f * 2.f * (float)M_PI + 0.3f;
				k.params[Kit::STRIKEX_PARAM].v = 0.55f * std::cos(th);
				k.params[Kit::STRIKEY_PARAM].v = 0.55f * std::sin(th);
				k.inst[0].drum.micR[0] = r; k.inst[0].drum.micR[1] = r;
				k.inst[0].drum.micAng[0] = 2.36f; k.inst[0].drum.micAng[1] = -0.79f;   // 135 / -45
				Stat s = measure(k, 0.5f, false);
				double c = s.lr / (std::sqrt(s.l * s.r) + 1e-30);
				cs += c; sm += (1 - c) / (1 + c + 1e-30);
				lv += db(std::sqrt(0.5 * (s.l + s.r) / s.n), std::sqrt(s.m / s.n));
				n++;
			}
			const sfs::MembraneShapes& sh = sfs::membraneShapes();
			for (int p = 0; p < KIT_NPRESET; p++) {
		if (KIT_PRESETS[p].engine) continue;   // the hi-hat: tools/kit-hat-check.cpp
				Kit k; k.loadPreset(p);
				k.inst[0].drum.sr = SR; k.inst[0].drum.clear(); k.control(); k.hit(0.7f);
				for (int t = 0; t < (int)(0.4f * SR); t++) {
					float h[2], w[2]; k.inst[0].drum.process(h, w, true);
					for (int q = 0; q < sfs::Drum::NM; q++) {
						int m = sfs::MEMBRANE_MODES[q].m;
						double v = k.inst[0].drum.lo[q].value() * sh.at(q, r);
						e[m == 0 ? 0 : m == 1 ? 1 : 2] += v * v;
					}
				}
			}
			double te = e[0] + e[1] + e[2] + 1e-30;
			printf("%.2f | %4.0f%% %4.0f%% %4.0f%% | %5.3f  %6.1f dB | %+6.2f dB\n",
			       r, 100*e[0]/te, 100*e[1]/te, 100*e[2]/te,
			       cs / n, 10 * std::log10(sm / n + 1e-9), lv / n);
		}
	} else if (!strcmp(mode, "grid")) {
		// Choosing the pair. Two points on a disc always have a perpendicular
		// bisector, and a strike anywhere along it is equidistant AND angularly
		// symmetric, so it reads identically at both mics: there are always two
		// directions on the head where the image is dead centre. That is not a
		// fault to design out -- it is a position, like any other -- but where
		// it falls relative to the DEFAULT strike is a choice, and the default
		// strike is straight up the head for every instrument in the module.
		// Land the null on it and the factory patch is mono; land the widest
		// point on it and every instrument is hard left out of the box.
		//
		// sep = how far apart the two mics are, in degrees round the rim.
		// off  = how far the pair's centre line sits from the default strike.
		printf("sep  off | default: lean  side | sweep: side  worst lean | sum\n");
		const int SEP[] = {60, 90, 120, 150, 180};
		const int OFF[] = {15, 25, 35, 45, 60, 75, 90};
		for (int i = 0; i < 5; i++) for (int j = 0; j < 7; j++) {
			float bis = (90.f + OFF[j]) * (float)M_PI / 180.f;
			float half = SEP[i] * 0.5f * (float)M_PI / 180.f;
			float aL = bis + half, aR = bis - half;
			if (std::cos(aL) > 0.f || std::cos(aR) < 0.f) continue;   // L left, R right
			double dl = 0, ds = 0, ss = 0, wl = 0, sm = 0; int n = 0;
			for (int p = 0; p < KIT_NPRESET; p++) {
		if (KIT_PRESETS[p].engine) continue;   // the hi-hat: tools/kit-hat-check.cpp
				Kit k; k.loadPreset(p);
				k.inst[0].drum.micAng[0] = aL; k.inst[0].drum.micAng[1] = aR;
				Stat s = measure(k, 0.6f, false);
				double L = std::sqrt(s.l / s.n), R = std::sqrt(s.r / s.n);
				double c = s.lr / (std::sqrt(s.l * s.r) + 1e-30);
				dl += db(L, R);
				ds += 10 * std::log10((1 - c) / (1 + c) + 1e-9);
			}
			dl /= KIT_NPRESET; ds /= KIT_NPRESET;
			for (int a = 0; a < 12; a++) {
				float th = (float)a / 12.f * 2.f * (float)M_PI;
				Kit k;
				k.params[Kit::STRIKEX_PARAM].v = 0.55f * std::cos(th);
				k.params[Kit::STRIKEY_PARAM].v = 0.55f * std::sin(th);
				k.inst[0].drum.micAng[0] = aL; k.inst[0].drum.micAng[1] = aR;
				Stat s = measure(k, 0.5f, false);
				double L = std::sqrt(s.l / s.n), R = std::sqrt(s.r / s.n);
				double c = s.lr / (std::sqrt(s.l * s.r) + 1e-30);
				ss += 10 * std::log10((1 - c) / (1 + c) + 1e-9);
				wl = std::max(wl, std::fabs(db(L, R)));
				sm = std::min(sm, db(std::sqrt(s.mono / s.n),
				                     std::sqrt(0.5 * (s.l + s.r) / s.n)));
				n++;
			}
			printf("%3d %4d | %+11.2f %5.1f | %10.1f %10.2f | %5.2f\n",
			       SEP[i], OFF[j], dl, ds, ss / n, wl, sm);
		}
	} else if (!strcmp(mode, "height")) {
		printf("mic height above the head, in radii. Lower is a stronger\n");
		printf("distance law -- more level swing -- and a marginally longer\n");
		printf("path difference. Higher is gentler and further away.\n\n");
		printf(" h   | default lean | widest lean |  sweep side | sum\n");
		for (int i = 0; i < 7; i++) {
			float hgt = 0.30f + 0.20f * i;
			double dl = 0, ss = 0, wl = 0, sm = 0; int n = 0;
			for (int p = 0; p < KIT_NPRESET; p++) {
		if (KIT_PRESETS[p].engine) continue;   // the hi-hat: tools/kit-hat-check.cpp
				Kit k; k.loadPreset(p); k.inst[0].drum.micH = hgt;
				Stat s = measure(k, 0.6f, false);
				dl += db(std::sqrt(s.l / s.n), std::sqrt(s.r / s.n));
			}
			dl /= KIT_NPRESET;
			for (int a = 0; a < 12; a++) {
				float th = (float)a / 12.f * 2.f * (float)M_PI;
				Kit k; k.inst[0].drum.micH = hgt;
				k.params[Kit::STRIKEX_PARAM].v = 0.55f * std::cos(th);
				k.params[Kit::STRIKEY_PARAM].v = 0.55f * std::sin(th);
				Stat s = measure(k, 0.5f, false);
				double L = std::sqrt(s.l / s.n), R = std::sqrt(s.r / s.n);
				double c = s.lr / (std::sqrt(s.l * s.r) + 1e-30);
				ss += 10 * std::log10((1 - c) / (1 + c) + 1e-9);
				wl = std::max(wl, std::fabs(db(L, R)));
				sm = std::min(sm, db(std::sqrt(s.mono / s.n),
				                     std::sqrt(0.5 * (s.l + s.r) / s.n)));
				n++;
			}
			printf("%.2f | %+12.2f | %+11.2f | %11.1f | %5.2f\n",
			       hgt, dl, wl, ss / n, sm);
		}
	} else if (!strcmp(mode, "mouse")) {
		// The mics are dragged on the head, so the screen and the head have to
		// agree about where things are. Two properties, both exactly checkable
		// and both the kind of thing that is invisible until someone tries to
		// grab a mic and cannot:
		//   ROUND TRIP -- put a mic at a screen point, and the mark must draw
		//   back at that point. A wrong inverse (the flat projection undone
		//   while the 3D view is showing, say -- which this widget got wrong
		//   once already) shows up here as a mic that slides away from the
		//   cursor as you drag it.
		//   GRAB -- the mark's own centre must hit-test as that mic, in both
		//   views, wherever it has been dragged to.
		printf("screen <-> head round trip, over both views\n\n");
		Kit k;
		Disp d; d.module = &k; d.S = d.cur();
		d.box.size = Vec(mm2px(101.58f), mm2px(45.71f));
		k.stereo = true;
		double worstRT = 0; int badGrab = 0, tested = 0, clamped = 0;
		for (int view = 0; view < 2; view++) {
			k.headView = view;
			float cx, cy, rad, sq; d.headFrame(cx, cy, rad, sq);
			for (int i = -6; i <= 6; i++) for (int j = -6; j <= 6; j++) {
				// a grid of screen points across the head, in head units
				float u = i / 6.f * 0.95f, v = j / 6.f * 0.95f;
				Vec p(cx + u * rad, cy + v * rad * sq);
				for (int c = 0; c < 2; c++) {
					d.placeMic(c, p);
					Vec m = d.micPos(c);
					float r = std::sqrt(u * u + v * v);
					// Points outside the mic's travel are SUPPOSED to move: the
					// clamp is the rim and centre limits, not an error.
					if (r > 0.10f && r < 0.92f) {
						double e = std::sqrt((double)(m.x - p.x) * (m.x - p.x)
						                   + (double)(m.y - p.y) * (m.y - p.y));
						worstRT = std::max(worstRT, e / mm2px(1.f));
					} else clamped++;
					if (d.micAt(m) != c) badGrab++;
					tested++;
				}
			}
		}
		printf("  worst round-trip error   %.4f mm  (over %d placements)\n", worstRT, tested);
		printf("  marks that did not grab  %d\n", badGrab);
		printf("  points outside the travel, correctly clamped  %d\n", clamped);
		// A mic must never be grabbable when stereo is off, or the head loses a
		// patch of its play surface for a mark that is not being drawn.
		k.stereo = false;
		d.placeMic(0, Vec(d.box.size.x * 0.5f, d.box.size.y * 0.5f));
		int offGrab = d.micAt(d.micPos(0));
		printf("  grabbable with stereo off  %s\n", offGrab < 0 ? "no" : "YES -- WRONG");
		bool ok = worstRT < 0.01 && badGrab == 0 && offGrab < 0;
		printf("\n%s\n", ok ? "the screen and the head agree"
		                    : "MISMATCH -- a dragged mic will not land where the cursor is");
		return ok ? 0 : 1;
	} else if (!strcmp(mode, "identity")) {
		// The invariant that keeps the two paths honest. Put BOTH mics exactly
		// where the strike is and every piece of the stereo path has to fall
		// away: cos(0) is 1, the level match finds the two sums already equal,
		// the two distances are the same so there is no delay and no level law.
		// What comes out of channel 0 must then be the mono engine, sample for
		// sample -- not close, EQUAL. Anything else means the taps carry a
		// different spectral tilt from the injection, or the compensation is
		// biased, or a delay line is reading off by one.
		printf("both mics at the strike point: stereo must collapse onto mono\n\n");
		double worst = 0;
		for (int i = 0; i < KIT_NPRESET; i++) {
			if (KIT_PRESETS[i].engine) continue;   // the hi-hat: tools/kit-hat-check.cpp
			Kit a; a.loadPreset(i); a.params[Kit::SNARE_PARAM].v = 0.6f;
			a.inst[0].drum.sr = SR; a.inst[0].drum.clear(); a.control();
			Kit b = a;
			b.inst[0].drum.micR[0] = b.inst[0].drum.micR[1] = b.inst[0].drum.strikeR;
			b.inst[0].drum.micAng[0] = b.inst[0].drum.micAng[1] = b.inst[0].drum.strikeAng;
			b.inst[0].drum.updateStrike();
			// Settle the air path before measuring. Moving the mics is a real
			// change of geometry and the engine answers it with a 2 ms
			// crossfade from the old distances -- correct, and not what this
			// test is asking about. Without this the first 96 samples measure
			// the fade and the invariant "fails" for the right reason.
			b.inst[0].drum.updateMics(); b.inst[0].drum.micXfade = 1.f;
			a.hit(0.7f); b.hit(0.7f);
			double w = 0;
			for (int n = 0; n < (int)(1.5f * SR); n++) {
				if (n == 9000) { a.hit(0.35f); b.hit(0.35f); }
				float ha[1], sa[1], hb[2], sb[2];
				a.inst[0].drum.process(ha, sa, false);
				b.inst[0].drum.process(hb, sb, true);
				w = std::max(w, (double)std::fabs(ha[0] - hb[0]));
				w = std::max(w, (double)std::fabs(sa[0] - sb[0]));
			}
			printf("  %-13s worst sample difference %.3g%s\n",
			       KIT_PRESETS[i].name, w, w == 0.0 ? "" : "   <-- FAILED");
			worst = std::max(worst, w);
		}
		printf("\n%s\n", worst == 0.0 ? "IDENTICAL -- the paths agree"
		                               : "CHANGED -- the stereo path is not a superset of mono");
		return worst == 0.0 ? 0 : 1;
	} else {
		printf("usage: h [presets|sweep|modes|radius|grid|height|mouse|identity]\n");
	}
	return 0;
}
'''

H = (H.replace('__PRESETS__', presetS + '\n' + presets + '\n' + npreset)
      .replace('__PARAMS__', paramE)
      .replace('__INPUTS__', inputE)
      .replace('__PV__', pv).replace('__XIN__', xinS).replace('__PUSH__', pushP).replace('__PRESET__', presetToSlotS).replace('__INST__', instS).replace('__KITN__', kitN)
      .replace('__LOADPRESET__', loadP)
      .replace('__CTL__', ctlblk)
      .replace('__STRIKE__', strikeL)
      .replace('__GEOM__', geom)
      .replace('__TILT__', tiltC)
      .replace('__SHELL__', shellC))
open(os.path.join(OUT, 'h.cpp'), 'w').write(H)
print("wrote " + os.path.join(OUT, 'h.cpp'))
