# Builds a standalone harness from src/sigma.cpp by EXTRACTING the real blocks.
# Nothing here is retyped: if a block cannot be found the generator fails loudly
# rather than silently testing a stale copy of the code.
#
#   cd /tmp && python3 <repo>/tools/sigma-envelope-harness.py
#   g++ -std=c++11 -O1 -o h h.cpp
#   ./h 1     # retrigger step per preset -- the VCA discontinuity
#   ./h 2     # attack time vs one cycle of each partial's own frequency
#   ./h 0     # summed peak level per preset, against the +/-10V clamp
#   ./h 8     # RATE: the tab's multiplier, the ENV RATE spread, sub-cycle decays
import re, sys, os
SRC = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'sigma.cpp')).read()
OUT = os.getcwd()          # writes h.cpp beside you, not into tools/

def grab(pat, label, flags=re.S):
    m = re.search(pat, SRC, flags)
    if not m: sys.exit("EXTRACT FAILED: " + label)
    return m.group(0)

def between(start, end, label):
    a = SRC.find(start)
    if a < 0: sys.exit("EXTRACT FAILED (start): " + label)
    b = SRC.find(end, a)
    if b < 0: sys.exit("EXTRACT FAILED (end): " + label)
    return SRC[a:b+len(end)]

advance   = grab(r'static void advance\(float& e.*?\n\t\}\n', 'advance()')
defaultFor= grab(r'static float defaultFor\(int tab, int p\) \{.*?\n\t\}\n', 'defaultFor()')
initSpec  = grab(r'void initSpectrum\(\) \{.*?\n\t\}\n', 'initSpectrum()')
helpers   = between('static float knobTime(float k', 'static float cutKnob', 'helpers')
helpers   = helpers[:helpers.rfind('static float cutKnob')] + \
            grab(r'static float cutKnob\(float hz\) \{.*?\n\t\}\n', 'cutKnob')
loadpre   = grab(r'\tvoid loadPreset\(int which\) \{.*?\n\t\}\n(?=\n)', 'loadPreset()')
paramenum = grab(r'enum ParamId \{.*?\n\t\};', 'ParamId')
stage     = grab(r'enum Stage \{[^}]*\};', 'Stage')
moddest   = grab(r'enum SgModDest \{.*?SG_MOD_N \};', 'SgModDest')
consts    = "\n".join(grab(r'static const int %s[^\n]*\n' % c, c) for c in
                      ['SG_MAXP','SG_VOICES','SG_MODSRC','SG_NPRESET'])
# the level chain, exactly as the engine runs it. Since 2026-09-25 it is two
# blocks: the envelope's share every sample, and the rest at control rate, with
# the product taken at the output -- so it is lifted as two and multiplied.
envblock  = between('float d = pDepth[p];',
                    'envAmt = -d * (V.envMax[p] - V.env[p]);\n\t\t\t\t}', 'envelope share')
lvblock   = between('float lv = pSoft[p] + (pLevel[p] - pSoft[p]) * morph;',
                    '(1.f - std::max(0.f, -oddEven));   // even', 'level chain')
levelchain = envblock + '\n' + lvblock + '\n\tlv *= envAmt;'
log2n     = grab(r'static inline float sgLog2n\(int n\) \{.*?\n\}', 'sgLog2n()')
# the rate multiplier is memoised in the engine; the formula inside the memo,
# verbatim, stands in for the array it fills
ratef     = grab(r'rateOwnP\[p\] = mRateOwn\[p\]\(pRate\[p\], \[\]\(float r\) \{ return (.*?); \}\);', 'rate formula')
ratef     = re.search(r'return (.*?); \}', ratef).group(1).replace(', r)', ', pRate[p])')
ratechain = between('float rateOwn = rateOwnP[p];',
                    'float rateDie = rateOwn * (1.f + envRate * (float)p * 0.35f);', 'rate')
ratechain = ratechain.replace('rateOwnP[p]', '(' + ratef + ')')

gatepass  = between('// \u2500\u2500 gate pass: channels strike voices',
                    'for (int c = nch; c < SG_VOICES; c++) chanVoice[c] = -1;', 'gate pass')

vrandfn   = grab(r'static inline float vrand\(uint32_t& st\) \{.*?\n\t\}', 'vrand()')
softclip  = grab(r'static inline float sgSoftClip\(float x\) \{.*?\n\}', 'sgSoftClip()')

H = r'''
// GENERATED by gen.py -- every block below is lifted verbatim from sigma.cpp.
#include <cmath>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <cstdint>
#include <algorithm>
#include "__FASTMATH__"
%(log2n)s
static float clamp(float v, float lo, float hi){ return v<lo?lo:(v>hi?hi:v); }
%(consts)s
%(moddest)s
static const char* SG_MODNAME[SG_MOD_N] = {"LVL","PIT","PAN","TLT","STR","CUT"};

%(softclip)s

struct P { float v=0.f; void setValue(float x){v=x;} float getValue()const{return v;} };

%(stage)s
struct Sigma {
	%(paramenum)s
	P params[PARAMS_LEN];
	float pLevel[SG_MAXP]={}, pSoft[SG_MAXP]={}, pPitch[SG_MAXP]={};
	float pPan[SG_MAXP]={}, pDepth[SG_MAXP]={}, pRate[SG_MAXP]={};
	float mod[SG_MODSRC][SG_MOD_N]={};
	int nPartials = 16;

	%(vrandfn)s
	%(defaultFor)s
	%(initSpec)s
	%(helpers)s
	%(loadpre)s
	%(advance)s
};

// The gate pass reads VEL; give it an input that reports 10V patched.
struct Voice {
	bool on = false; float vel = 1.f, pitch = 0.f;
	float env[SG_MAXP] = {}; int stage[SG_MAXP] = {}; float wait[SG_MAXP] = {};
	float relFrom[SG_MAXP] = {}; float envMax[SG_MAXP] = {};
	float mEnv = 0.f; int mStage = 0; float mRelFrom = 0.f;
	float ampGain = 1.f;
	int ctl = 0;     // sigma.cpp: the partial-resolve countdown the gate pass resets
	float lfoPh[3] = {}, rndCur[3] = {}, rndNext[3] = {};
	uint32_t rng = 1u; float age = 0.f;
};

// The REAL gate pass, lifted whole, with just enough around it to run.
struct Poly {
	int nch = 1; float g[16] = {}; float v[16] = {}; bool conn = true;
	int getChannels() const { return nch; }
	bool isConnected() const { return conn; }
	float getVoltage(int c = 0) const { return g[c]; }
	float getPolyVoltage(int c) const { return nch == 1 ? g[0] : g[c]; }
};
struct Rig {
	Voice voice[SG_VOICES];
	int chanVoice[SG_VOICES];
	int nPartials = 16;
	float envSpr = 0.f;
	enum { ALLOC_FIRST, ALLOC_ROLL };
	int allocMode = ALLOC_FIRST;
	int rollNext = 0;
	P params[Sigma::PARAMS_LEN];
	float lfoPhase[3] = {};
	static float touch(float v, float sn, float c) { return Sigma::touch(v, sn, c); }
	static float vrand(uint32_t& st) { return Sigma::vrand(st); }
	Poly gateIn, voctIn, velIn;
	Rig() { for (int v = 0; v < SG_VOICES; v++) chanVoice[v] = -1; }
	void tick() {
		int nch = gateIn.getChannels();
		struct { Poly& operator[](int i) { return *p[i]; } Poly* p[3]; } inputs{{&gateIn,&voctIn,&velIn}};
		const int GATE_INPUT = 0, VOCT_INPUT = 1, VEL_INPUT = 2;
		const int AMPSENS_PARAM = Sigma::AMPSENS_PARAM;
		const int AMPCENTER_PARAM = Sigma::AMPCENTER_PARAM;
		const int LFORAND_PARAM = Sigma::LFORAND_PARAM;
		(void)GATE_INPUT; (void)VOCT_INPUT; (void)VEL_INPUT;
		%(gatepass)s
		for (int c = nch; c < SG_VOICES; c++) chanVoice[c] = -1;
	}
};

static const char* NAME[SG_NPRESET] = {
	"Ramp","Square","Organ","E-piano","Vibraphone","Marimba","Bell",
	"TubularBells","SingingBowl","Gong","PsychGong","Bowed","Choir","Vowel",
	"CS-80","TouchSwitch","Bloom","Cloud","Rotor","Acid","Ensemble"};

// The level chain for ONE partial, verbatim, at a given envelope value.
static float levelOf(Sigma& m, int p, float env, float morph,
                     float tilt, float oddEven, float envRate) {
	int n = p + 1;
	(void)envRate;
	float* pSoft = m.pSoft; float* pLevel = m.pLevel; float* pDepth = m.pDepth;
	float V_env_p = env;
	float V_emax_p = env;   // at the envelope's own peak, so a bloom is silent
	%(levelchain_body)s
	return lv;
}

int main(int argc, char** argv) {
	int mode = argc > 1 ? atoi(argv[1]) : 0;
	Sigma m;

	if (mode == 3) {
		// ---- VOICE ALLOCATION, through the real gate pass.
		// A MONO gate line striking eight notes: each must take a DIFFERENT
		// voice while the previous ones are still ringing, and each voice must
		// keep the pitch it was struck at even though V/OCT moves on.
		Rig r;
		r.gateIn.nch = 1; r.voctIn.nch = 1; r.velIn.conn = false;
		printf("note  v/oct   -> voice   latched pitch   distinct voices so far\n");
		int seen[SG_VOICES] = {0}, distinct = 0;
		bool ok = true;
		for (int n = 0; n < 8; n++) {
			float pitch = n * (1.f / 12.f);
			r.voctIn.g[0] = pitch;
			r.gateIn.g[0] = 10.f; r.tick();            // strike
			int v = r.chanVoice[0];
			float latched = v >= 0 ? r.voice[v].pitch : -99.f;
			r.gateIn.g[0] = 0.f;  r.tick();            // release; voice rings on
			// V/OCT moves to the next note while the last is still sounding --
			// this is exactly what dragged the pitch before it was latched.
			r.voctIn.g[0] = pitch + 0.5f;
			if (v >= 0 && !seen[v]) { seen[v] = 1; distinct++; }
			bool held = v >= 0 && std::fabs(r.voice[v].pitch - latched) < 1e-6f;
			if (!held) ok = false;
			printf("%%4d  %%6.3f   ->  %%3d     %%7.4f %%s   %%d\n", n, pitch, v, 
			       r.voice[v].pitch, held ? "held" : "DRAGGED", distinct);
		}
		printf("\n%%d of 8 notes on distinct voices; pitch %%s\n",
		       distinct, ok ? "latched on every one" : "DRAGGED on at least one");
		// and a poly gate must still behave
		Rig q; q.gateIn.nch = 4; q.voctIn.nch = 4;
		for (int c = 0; c < 4; c++) { q.gateIn.g[c] = 10.f; q.voctIn.g[c] = c * 0.25f; }
		q.tick();
		printf("poly gate, 4 channels -> voices %%d %%d %%d %%d, pitches %%.2f %%.2f %%.2f %%.2f\n",
		       q.chanVoice[0], q.chanVoice[1], q.chanVoice[2], q.chanVoice[3],
		       q.voice[q.chanVoice[0]].pitch, q.voice[q.chanVoice[1]].pitch,
		       q.voice[q.chanVoice[2]].pitch, q.voice[q.chanVoice[3]].pitch);
	}
	else 	if (mode == 7) {
		// ---- THE ATTACK TRANSIENT. What fraction of the sound in the first
		// few milliseconds comes from the INVERTED partials? They are the high
		// inharmonic ones, so if they dominate the onset the note begins with a
		// burst of the wrong spectrum -- which is what a squelch is.
		const float dt = 1.f / 48000.f;
		int which[3] = {9, 16, 17};                 // Gong, Bloom, Cloud
		printf("preset       inverted partials' share -- OLD (1+d*env) vs NEW (-d*(max-env))\n");
		printf("             t=0.5ms      t=3ms       t=30ms       t=1s        t=4s\n");
		for (int wi = 0; wi < 3; wi++) {
			m.loadPreset(which[wi]);
			float A = 0.001f * std::pow(8000.f, m.params[Sigma::ATTACK_PARAM].getValue());
			float D = 0.005f * std::pow(2400.f, m.params[Sigma::DECAY_PARAM].getValue());
			float S = m.params[Sigma::SUSTAIN_PARAM].getValue();
			float R = 0.005f * std::pow(3200.f, m.params[Sigma::RELEASE_PARAM].getValue());
			float er = m.params[Sigma::ENVRATE_PARAM].getValue();
			float spr = m.params[Sigma::ENVSPREAD_PARAM].getValue();
			int np = m.nPartials;
			float env[SG_MAXP], emax[SG_MAXP], wait[SG_MAXP], rf[SG_MAXP]; int stg[SG_MAXP];
			for (int p = 0; p < np; p++) {
				env[p] = 0.f; emax[p] = 0.f; stg[p] = 1; rf[p] = 0.f;
				float f = (float)p / (float)(np - 1);
				wait[p] = std::fabs(spr) * 0.25f * (spr >= 0.f ? f : 1.f - f);
			}
			printf("%%-12s", NAME[which[wi]]);
			const float MK[5] = {0.0005f, 0.003f, 0.03f, 1.f, 4.f};
			int k = 0;
			for (float t = 0.f; t <= 4.001f && k < 5; t += dt) {
				for (int p = 0; p < np; p++) {
					float own = 0.25f * std::pow(16.f, m.pRate[p]);
					float die = own * (1.f + er * (float)p * 0.35f);
					if (wait[p] > 0.f) wait[p] -= dt;
					else Sigma::advance(env[p], stg[p], rf[p], own, die, dt, A, D, S, R);
					if (env[p] > emax[p]) emax[p] = env[p];
				}
				if (std::fabs(t - MK[k]) > dt * 0.5f) continue;
				double inv = 0, tot = 0, oinv = 0, otot = 0;
				for (int p = 0; p < np; p++) {
					float d = m.pDepth[p];
					float amt = (d >= 0.f) ? (1.f - d + d * env[p]) : (-d * (emax[p] - env[p]));
					float old = (d >= 0.f) ? (1.f - d + d * env[p]) : (1.f + d * env[p]);
					float lv = m.pLevel[p] * (amt > 0.f ? amt : 0.f);
					float ol = m.pLevel[p] * (old > 0.f ? old : 0.f);
					tot += lv; otot += ol;
					if (d < 0.f) { inv += lv; oinv += ol; }
				}
				printf("  %%5.1f->%%4.1f%%%%", otot > 1e-9 ? 100.0 * oinv / otot : 0.0,
				       tot > 1e-9 ? 100.0 * inv / tot : 0.0);
				k++;
			}
			printf("\n");
		}
	}
	else 	if (mode == 6) {
		// ---- SPECTRAL CENTROID OVER THE TAIL. No partial in Sigma ever changes
		// pitch, so a tail that seems to bend is the centre of MASS moving as
		// partials die at different rates. This measures it directly, in
		// semitones relative to the centroid at the moment of the strike.
		const float dt = 1.f / 48000.f;
		int which[2] = {10, 9};                      // Psychedelic Gong, Gong
		for (int wi = 0; wi < 2; wi++) {
			m.loadPreset(which[wi]);
			float A = 0.001f * std::pow(8000.f, m.params[Sigma::ATTACK_PARAM].getValue());
			float D = 0.005f * std::pow(2400.f, m.params[Sigma::DECAY_PARAM].getValue());
			float S = m.params[Sigma::SUSTAIN_PARAM].getValue();
			float R = 0.005f * std::pow(3200.f, m.params[Sigma::RELEASE_PARAM].getValue());
			float er = m.params[Sigma::ENVRATE_PARAM].getValue();
			float st = m.params[Sigma::STRETCH_PARAM].getValue();
			float spr = m.params[Sigma::ENVSPREAD_PARAM].getValue();
			float B = st * st * 0.02f;
			int np = m.nPartials;
			float env[SG_MAXP], wait[SG_MAXP]; int stg[SG_MAXP]; float rf[SG_MAXP];
			for (int p = 0; p < np; p++) {
				env[p] = 0.f; stg[p] = 1; rf[p] = 0.f;
				float f = (float)p / (float)(np - 1);
				wait[p] = std::fabs(spr) * 0.25f * (spr >= 0.f ? f : 1.f - f);
			}
			float cen[5] = {0,0,0,0,0};
			for (float t = 0.f; t <= 6.001f; t += dt) {
				for (int p = 0; p < np; p++) {
					float own = 0.25f * std::pow(16.f, m.pRate[p]);
					float die = own * (1.f + er * (float)p * 0.35f);
					if (wait[p] > 0.f) wait[p] -= dt;
					else Sigma::advance(env[p], stg[p], rf[p], own, die, dt, A, D, S, R);
				}
				static const float MARK[5] = {0.25f, 0.5f, 1.5f, 3.f, 6.f};
				for (int k = 0; k < 5; k++) {
					if (std::fabs(t - MARK[k]) > dt * 0.5f) continue;
					double num = 0, den = 0;
					for (int p = 0; p < np; p++) {
						float n = (float)(p + 1);
						float fr = n * std::sqrt(1.f + B * n * n) * 261.6f;
						if (fr >= 24000.f) continue;
						float d = m.pDepth[p];
						float amt = (d >= 0.f) ? (1.f - d + d * env[p]) : (1.f + d * env[p]);
						float lv = m.pLevel[p] * amt;
						cen[k] += (lv > 0.f) ? 0.f : 0.f;
						if (lv < 0.f) lv = 0.f;
						num += (double)fr * lv; den += lv;
					}
					cen[k] = den > 0 ? (float)(num / den) : 1.f;
				}
			}
			// baselined at 0.5s: at 0.25s the note is still speaking and with
			// ENV SPREAD not every partial has even started, so the centroid
			// there is not a pitch anyone hears yet.
			printf("%%-11s ", NAME[which[wi]]);
			static const float MK[5] = {0.25f, 0.5f, 1.5f, 3.f, 6.f};
			for (int k = 0; k < 5; k++)
				printf("t=%%.2f %%+6.2f  ", MK[k], 12.f * std::log2(std::max(cen[k],1.f) / std::max(cen[1],1.f)));
			printf("\n");
			printf("            drift 0.5s -> 6s: %%+.1f semitones\n",
			       12.f * std::log2(std::max(cen[4],1.f) / std::max(cen[1],1.f)));
			printf("\n");
		}
	}
	else 	if (mode == 5) {
		// ---- ALLOCATION MODES. The two only differ once voices START COMING
		// BACK: first-available rescans from voice 0 and so keeps landing on the
		// same one, where rolling carries on round the ring. That is the whole
		// point -- a repeated note on a long tail is cut by its own repeat.
		const float dt = 1.f / 48000.f;
		const float A = 0.002f, D = 0.15f, S = 0.f, R = 0.12f;   // short, so they finish
		for (int mode2 = 0; mode2 < 2; mode2++) {
			Rig r; r.gateIn.nch = 1; r.velIn.conn = false;
			r.allocMode = mode2;
			printf("%%s: 10 repeated notes take voices", mode2 ? "ROLLING        " : "FIRST AVAILABLE");
			int seen[SG_VOICES] = {0}, distinct = 0;
			for (int n = 0; n < 10; n++) {
				r.gateIn.g[0] = 10.f; r.tick();
				int v = r.chanVoice[0];
				printf(" %%2d", v);
				if (!seen[v]) { seen[v] = 1; distinct++; }
				r.gateIn.g[0] = 0.f; r.tick();
				for (int k = 0; k < (int)(0.35f / dt); k++)     // let it finish
					for (int w = 0; w < SG_VOICES; w++)
						Sigma::advance(r.voice[w].mEnv, r.voice[w].mStage,
						               r.voice[w].mRelFrom, 1.f, 1.f, dt, A, D, S, R);
			}
			printf("   -> %%d distinct\n", distinct);
		}
		// PERIODIC LOCKS, APERIODIC DRIFTS -- the Synergy's rule, checked.
		for (int rnd = 0; rnd < 2; rnd++) {
			Rig r; r.gateIn.nch = 4;
			for (int i = 0; i < 3; i++)
				r.params[Sigma::LFORAND_PARAM + i].setValue(rnd ? 0.5f : 0.f);
			r.lfoPhase[0] = 0.37f;
			for (int c = 0; c < 4; c++) r.gateIn.g[c] = 10.f;
			r.tick();
			printf("LFO random %%.1f -> voice phases", rnd ? 0.5f : 0.f);
			bool same = true;
			for (int c = 0; c < 4; c++) {
				float ph = r.voice[r.chanVoice[c]].lfoPh[0];
				printf(" %%.3f", ph);
				if (std::fabs(ph - r.lfoPhase[0]) > 1e-6f) same = false;
			}
			printf("   %%s\n", same ? "locked to the shared phase" : "each independent");
		}
	}
		else if (mode == 4) {
		// ---- TOUCH RESPONSE, through the real curves.
		printf("AMPLITUDE  touch(vel, sens, centre) -- level, 0..1\n");
		printf("  sens  centre   v=0.0  v=0.25  v=0.5  v=0.75  v=1.0\n");
		float SC[4][2] = {{0.f,0.8f},{0.3f,0.8f},{0.6f,0.8f},{1.f,0.5f}};
		for (int i = 0; i < 4; i++) {
			printf("  %%.2f  %%.2f  ", SC[i][0], SC[i][1]);
			for (float v = 0.f; v <= 1.001f; v += 0.25f)
				printf("  %%6.3f", Sigma::touch(v, SC[i][0], SC[i][1]));
			printf("%%s\n", SC[i][0] < 0.001f ? "   <- sens 0: centre IS the level" : "");
		}
		printf("\nTIMBRE  touchMorph(vel, sens, 0.5) -- morph, 0..1\n");
		printf("  sens    v=0.0  v=0.25  v=0.4  v=0.5  v=0.6  v=0.75  v=1.0\n");
		float SS[5] = {0.f, 0.25f, 0.5f, 0.75f, 1.f};
		for (int i = 0; i < 5; i++) {
			printf("  %%.2f  ", SS[i]);
			const float VV[7] = {0.f,0.25f,0.4f,0.5f,0.6f,0.75f,1.f};
			for (int k = 0; k < 7; k++)
				printf("  %%6.3f", Sigma::touchMorph(VV[k], SS[i], 0.5f));
			printf("%%s\n", i == 2 ? "   <- widest blend" : (i == 4 ? "   <- a switch" : ""));
		}
		// the claim that 0.5 reproduces the old `vel + morphK`
		float worst = 0.f;
		for (int k = 0; k <= 100; k++) {
			float v = k / 100.f;
            float old_ = v < 0.f ? 0.f : (v > 1.f ? 1.f : v);
			worst = std::max(worst, std::fabs(Sigma::touchMorph(v, 0.5f, 0.5f) - old_));
		}
		printf("\nsens 0.5 vs the old vel+morphK: worst difference %%.6f\n", worst);
		printf("\nSOFT CLIP\n   in     out    (hard clamp)\n");
		for (float v : {3.f, 6.f, 6.92f, 10.82f, 13.84f, 27.7f})
			printf("  %%5.2f  %%5.2f      %%5.2f\n", v, sgSoftClip(v), v > 10.f ? 10.f : v);
	}
	else 	if (mode == 8) {
		// ---- RATE, three questions.
		//
		// (1) Does the RATE tab do what its tooltip claims? It reads
		//     "0.25x .. 4x" with centre 1x.
		// (2) Does ENV RATE leave the ATTACK alone? Its whole meaning is
		//     "highs die sooner", and it used to multiply the attack too.
		// (3) Does the spread ever make a DECAY shorter than one cycle of the
		//     partial that is decaying? That is the same failure the attack
		//     had: an envelope segment shorter than a cycle is a step, however
		//     smooth the maths.
		float dt = 1.f / 48000.f;
		printf("(1) RATE tab multiplier, from the extracted formula\n");
		{
			float envRate = 0.f; int p = 0;
			for (int k = 0; k <= 4; k++) {
				m.pRate[0] = (float)k * 0.25f;
				%(ratechain_body)s
				printf("    pRate %%.2f -> rateOwn %%.2fx   rateDie %%.2fx\n",
				       m.pRate[0], rateOwn, rateDie);
			}
		}

		printf("\n(2) attack time, ENV RATE 0 vs 1 (must be identical)\n");
		for (int i = 0; i < SG_NPRESET; i++) {
			m.loadPreset(i);
			float A = Sigma::knobTime(m.params[Sigma::ATTACK_PARAM].getValue(), 0.001f, 8.f);
			float D = Sigma::knobTime(m.params[Sigma::DECAY_PARAM].getValue(),  0.005f, 12.f);
			float S = m.params[Sigma::SUSTAIN_PARAM].getValue();
			float R = Sigma::knobTime(m.params[Sigma::RELEASE_PARAM].getValue(),0.005f, 16.f);
			int top = m.nPartials - 1;
			float t[2];
			for (int e = 0; e < 2; e++) {
				float envRate = (float)e; int p = top;
				%(ratechain_body)s
				float env = 0.f, rel = 0.f; int st = ST_ATT; int n = 0;
				while (st == ST_ATT && n < 48000 * 20) { Sigma::advance(env, st, rel, rateOwn, rateDie, dt, A, D, S, R); n++; }
				t[e] = (float)n * dt;
			}
			if (std::fabs(t[0] - t[1]) > 1e-9f)
				printf("    %%-16s ATTACK MOVED: %%.4f ms -> %%.4f ms  <-- BUG\n",
				       NAME[i], t[0]*1000.f, t[1]*1000.f);
		}
		printf("    (no lines above = attack is independent of ENV RATE)\n");

		printf("\n(3) decay of the top partial vs one cycle of its own pitch\n");
		printf("    preset            np   envRate  decay(ms)  cycles  \n");
		for (int i = 0; i < SG_NPRESET; i++) {
			m.loadPreset(i);
			float A = Sigma::knobTime(m.params[Sigma::ATTACK_PARAM].getValue(), 0.001f, 8.f);
			float D = Sigma::knobTime(m.params[Sigma::DECAY_PARAM].getValue(),  0.005f, 12.f);
			float S = m.params[Sigma::SUSTAIN_PARAM].getValue();
			float R = Sigma::knobTime(m.params[Sigma::RELEASE_PARAM].getValue(),0.005f, 16.f);
			// A preset with full sustain has NO decay segment: the envelope goes
			// attack straight to sustain, and "time until the decay ends" is one
			// sample. Reporting that as a sub-cycle decay is crying wolf, and a
			// checker that cries wolf is how a real finding gets missed.
			if (S >= 0.999f) { printf("    %%-16s  %%3d     --      (sustain 1.0, no decay segment)\n", NAME[i], m.nPartials); continue; }
			for (int e = 0; e < 2; e++) {
				float envRate = e ? 1.f : m.params[Sigma::ENVRATE_PARAM].getValue();
				int p = m.nPartials - 1;
				%(ratechain_body)s
				// straight to the decay segment: this is about the decay only
				float env = 1.f, rel = 0.f; int st = ST_DEC; int n = 0;
				while (st == ST_DEC && n < 48000 * 30) { Sigma::advance(env, st, rel, rateOwn, rateDie, dt, A, D, S, R); n++; }
				float secs = (float)n * dt;
				float cyc = secs * (float)(p + 1) * 261.6f;
				printf("    %%-16s  %%3d   %%5.2f    %%8.2f  %%7.1f%%s\n",
				       NAME[i], m.nPartials, envRate, secs*1000.f, cyc,
				       cyc < 1.f ? "   <-- sub-cycle decay" : "");
			}
		}
	}
	else 	if (mode == 2) {
		// ---- ATTACK: how long the VCA takes to open, and how that compares
		// with one cycle of a middle C. An attack much shorter than a cycle is
		// a step as far as the fundamental is concerned, however smooth the
		// envelope maths is. Also the FASTEST per-partial attack, because the
		// ENV RATE spread multiplies the attack as well as the decay.
		// Compared against EACH PARTIAL'S OWN cycle, which is the honest test:
		// a 0.5 ms attack is half a cycle for the fundamental but two and a half
		// for the sixteenth partial, and it is the partial that is opening.
		printf("preset      master A    worst partial: A / its own period\n");
		for (int i = 0; i < SG_NPRESET; i++) {
			m.loadPreset(i);
			float A  = 0.001f * std::pow(8000.f, m.params[Sigma::ATTACK_PARAM].getValue());
			float worst = 1e9f; int wp = 0;
			for (int p = 0; p < m.nPartials; p++) {
				float rateOwn = 0.25f * std::pow(16.f, m.pRate[p]);
				float cyc = (A / rateOwn) * (float)(p + 1) * 261.6f;
				if (cyc < worst) { worst = cyc; wp = p + 1; }
			}
			printf("%%-10s  %%7.2f ms   %%6.2f cycles (partial %%2d)%%s\n",
			       NAME[i], A*1000.f, worst, wp,
			       worst < 0.5f ? "   <-- still a step" : "");
		}
	}
	else 	if (mode == 0) {
		// ---- PEAK SUM: what the summed partials reach before the output trim.
		printf("preset        np     peak      rms(loudness)\n");
		for (int i = 0; i < SG_NPRESET; i++) {
			m.loadPreset(i);
			float tilt = m.params[Sigma::TILT_PARAM].getValue();
			float oe   = m.params[Sigma::ODDEVEN_PARAM].getValue();
			float er   = m.params[Sigma::ENVRATE_PARAM].getValue();
			float sum = 0.f, sq = 0.f;
			for (int p = 0; p < m.nPartials; p++) {
				float lv = std::fabs(levelOf(m, p, 1.f, 1.f, tilt, oe, er));
				sum += lv; sq += lv * lv;
			}
			// PEAK is every partial aligned, which happens rarely; LOUDNESS
			// tracks RMS, and incoherent partials add as the root of the sum of
			// squares. Judging preset balance by peak overstates how much
			// louder a many-partial preset really is.
			float peak = sum * 1.6f;
			float rms = std::sqrt(sq * 0.5f) * 1.6f;
			printf("%%-12s %%3d  %%7.2f V  %%7.2f V   %%s\n", NAME[i], m.nPartials,
			       peak, rms, peak > 10.f ? "PEAK CLIPS" : "");
		}
	}
	else {
		// ---- VOICE STEALING. With allocation in place, a plain retrigger takes
		// a FRESH voice, so the only way a still-sounding voice gets re-attacked
		// is when every one of the sixteen is busy and the quietest is stolen.
		// `g = V.mEnv` IS the VCA, so whatever step mEnv takes across that
		// note-on is the click.
		printf("preset      stolen VCA before   after   STEP\n");
		const float dt = 1.f / 48000.f;
		float worst = 0.f;
		for (int i = 0; i < SG_NPRESET; i++) {
			m.loadPreset(i);
			float A = 0.001f * std::pow(8000.f, m.params[Sigma::ATTACK_PARAM].getValue());
			float D = 0.005f * std::pow(2400.f, m.params[Sigma::DECAY_PARAM].getValue());
			float S = m.params[Sigma::SUSTAIN_PARAM].getValue();
			float R = 0.005f * std::pow(3200.f, m.params[Sigma::RELEASE_PARAM].getValue());
			Rig r;
			r.nPartials = m.nPartials;
			r.envSpr = m.params[Sigma::ENVSPREAD_PARAM].getValue();
			r.gateIn.nch = 1;
			// Fill all sixteen so they are RINGING, which means actually running
			// their envelopes -- striking and releasing without advancing left
			// every mEnv at zero, so the steal below had nothing to steal from
			// and the test passed by testing nothing.
			for (int n = 0; n < SG_VOICES; n++) {
				r.gateIn.g[0] = 10.f; r.tick();
				for (int k = 0; k < (int)(0.08f / dt); k++)      // hold 80ms
					for (int v = 0; v < SG_VOICES; v++)
						Sigma::advance(r.voice[v].mEnv, r.voice[v].mStage,
						               r.voice[v].mRelFrom, 1.f, 1.f, dt, A, D, S, R);
				r.gateIn.g[0] = 0.f;  r.tick();
			}
			// the quietest is the one the allocator will take
			int q = 0;
			for (int v = 1; v < SG_VOICES; v++)
				if (r.voice[v].mEnv < r.voice[q].mEnv) q = v;
			float before = r.voice[q].mEnv;
			r.gateIn.g[0] = 10.f; r.tick();               // the steal
			int got = r.chanVoice[0];
			float after = r.voice[got].mEnv;
			float step = std::fabs(after - before);
			if (got != q) step = 0.f;                     // took an idle one instead
			if (step > worst) worst = step;
			printf("%%-10s        %%6.4f      %%6.4f    %%6.4f%%s\n", NAME[i],
			       before, after, step, step > 0.01f ? "   <-- CLICK" : "");
		}
		printf("\nworst steal step: %%.4f  (1.0 = full scale)\n", worst);
	}
	return 0;
}
'''
# the level chain needs V.env[p] renamed to a plain local
lc = levelchain.replace('V.envMax[p]', 'V_emax_p').replace('V.env[p]', 'V_env_p')
H = H.replace('__FASTMATH__', os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'fastmath.hpp'))
open(os.path.join(OUT,'h.cpp'),'w').write(H % dict(
    consts=consts, moddest=moddest, paramenum=paramenum, defaultFor=defaultFor,
    initSpec=initSpec, stage=stage, helpers=helpers, loadpre=loadpre, advance=advance, softclip=softclip, vrandfn=vrandfn, gatepass=gatepass,
    levelchain_body=lc, log2n=log2n,
    ratechain_body=ratechain.replace('pRate[p]', 'm.pRate[p]')))
print("generated; extracted %d blocks verbatim" % 9)
