# Builds a standalone harness from src/wheel.cpp by EXTRACTING the real blocks.
# Nothing here is retyped: if a block cannot be found the generator fails loudly
# rather than silently testing a stale copy of the code.
#
#   cd /tmp && python3 <repo>/tools/wheel-dog-harness.py
#   g++ -std=c++11 -O1 -o h h.cpp
#   ./h 1     # which strokes of the turn fire, across DOG and across CRANK
#   ./h 2     # the ripple profile: shape, depth, and the seam
import re, sys, os
SRC = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', 'src', 'wheel.cpp')).read()
OUT = os.getcwd()

def grab(pat, label, flags=re.S):
    m = re.search(pat, SRC, flags)
    if not m: sys.exit("EXTRACT FAILED: " + label)
    return m.group(0)

def between(start, end, label):
    a = SRC.find(start)
    if a < 0: sys.exit("EXTRACT FAILED (start): " + label)
    b = SRC.find(end, a)
    if b < 0: sys.exit("EXTRACT FAILED (end): " + label)
    return SRC[a:b + len(end)]

seam   = grab(r'static const float WH_SEAM = [0-9.]+f;', 'WH_SEAM')
justtab= grab(r'static const float WH_JUST\[12\] = \{.*?\};', 'WH_JUST')
justfn = grab(r'static inline float wheelJustify\(float semis\) \{.*?\n\}', 'wheelJustify()')
maxc   = grab(r'static const int WH_MAXCOUPS = \d+;[^\n]*', 'WH_MAXCOUPS')
gcdfn  = grab(r'static inline int wheelGcd\(int a, int b\) \{[^\n]*\}', 'wheelGcd()')
accent = grab(r'static inline float wheelAccent\(int k, int n\) \{.*?\n\}', 'wheelAccent()')
# The two places the ripple reaches the sound, lifted as expressions so mode 3
# measures what the engine actually applies rather than a description of it.
press  = grab(r'struct WheelPress \{.*?\n\};', 'WheelPress')
ampF   = grab(r'clamp\(1\.f \+ depth \* r \* [0-9.]+f, [0-9.]+f, [0-9.]+f\)', 'ripple->amp')
brightF= grab(r'clamp\(1\.f \+ [0-9.]+f \* depth \* r, [0-9.]+f, [0-9.]+f\)', 'ripple->bright')
ripple = grab(r'\tfloat rippleAt\(double ph\) const \{.*?\n\t\}', 'rippleAt()')

# The crank/coup/dog block, exactly as process() runs it. Cut at the boundaries
# of the two sections so the harness cannot drift from the engine.
crank = between('\t\tdouble prevPhase = wheelPhase;',
                '\t\tfloat rattleGate = (rattle < 0.42) ? 1.f : 0.f;', 'crank+coup+dog')
# strip the two lines that need Rack inputs; the harness drives them directly
crank = crank.replace(
    '\t\tif (coupTrig.process(inputs[COUP_INPUT].getVoltage(), 0.1f, 1.f)) stroke = 1.2f;',
    '\t\tif (coupIn) stroke = 1.2f;')
crank = re.sub(r'\t\tfloat dogK = params\[DOG_PARAM\]\.getValue\(\);\n'
               r'\t\tif \(inputs\[DOG_INPUT\]\.isConnected\(\)\).*?\n'
               r'\t\tdogK = clamp\(dogK, 0\.f, 1\.f\);\n', '', crank)
crank = re.sub(r'\t\tfloat decayS = 0\.04f \+ 0\.11f \* params\[DECAY_PARAM\]\.getValue\(\);',
               '\t\tfloat decayS = 0.04f + 0.11f * 0.4f;', crank)
# COUPS is read above the extracted range, so the harness sets `coups` itself.
# `random` is a function in macOS's <stdlib.h>, so the namespace is renamed
# rather than shadowed. A pure rename: no behaviour rides on it.
crank = crank.replace('random::', 'rnd::')
if 'dogK' not in crank:            sys.exit("EXTRACT FAILED: dogK vanished with the strip")
if 'params[DOG_PARAM]' in crank:   sys.exit("EXTRACT FAILED: dogK read not stripped")
if 'inputs[' in crank:             sys.exit("EXTRACT FAILED: an unsubstituted Rack input remains")
if 'params[' in crank:             sys.exit("EXTRACT FAILED: an unsubstituted Rack param remains")

H = r'''
// GENERATED by tools/wheel-dog-harness.py -- every block below is lifted
// verbatim from src/wheel.cpp.
#include <cmath>
#include <cstdio>
#include <cstring>
#include <algorithm>
#include "__FASTMATH__"   // rippleAt() uses the polynomial sine (2026-09)
extern "C" int atoi(const char*);
extern "C" double atof(const char*);
static float clamp(float v, float lo, float hi){ return v<lo?lo:(v>hi?hi:v); }
static int   clamp(int v, int lo, int hi){ return v<lo?lo:(v>hi?hi:v); }
namespace rnd { static unsigned s=1; 
  static float uniform(){ s=s*1664525u+1013904223u; return (s>>8)*(1.f/16777216.f); }
  static float normal(){ float a=uniform(), b=uniform();
    if(a<1e-7f) a=1e-7f; return std::sqrt(-2.f*std::log(a))*std::cos(6.2831853f*b); } }

%(seam)s
%(justtab)s
%(justfn)s
%(maxc)s
%(gcdfn)s
%(accent)s
%(press)s

struct Rig {
  double wheelPhase=0.0;
  float speed=1.6f, speedBase=1.6f;
  float impulse=0.f, impulseTgt=0.f;
  float buzzEnv=0.f, clickEnv=0.f, dogHold=0.f, dogFlash=0.f;
  sfs::Memo mImp, mClick, mDog, mSlot, mSwell; sfs::Memo2 mBuzz;   // wheel.cpp's memoised decays
  float slotFlash[WH_MAXCOUPS]={};
  float dogThresh=0.44f, strokeGain=1.f;
  double rattle=0.0;
  int coups=4, coupSlot=0; unsigned char coupMask=0xFF;
  bool coupIn=false; float dogK=0.35f;
  int fires=0; int fireSlot[64]; int nfire=0;
  struct { void trigger(float){} } coupPulse;

%(ripple)s

  void step(float dt){
%(crank)s
    (void)rattleGate;
  }
};

static void run6(){
  printf("what TEMPER actually moves, in cents, per scale degree\n\n");
  printf("  semitones from the root:  0   1    2    3    4    5    6    7    8    9   10   11\n");
  printf("  TEMPER shift (cents):  ");
  for(int k=0;k<12;k++) printf("%%5.1f", (wheelJustify((float)k)-(float)k)*100.f);
  printf("\n\n");
  // the voicing the module ships with
  const int deg[6]={0,4,0,2,0,0}, oct[6]={0,0,0,1,0,1};
  const float MAJ[7]={0,2,4,5,7,9,11};
  const char* nm[6]={"1 root","2","3","4","5","trompette"};
  printf("  the DEFAULT voicing, in C major:\n");
  float worst=0.f;
  for(int v=0;v<6;v++){
    float semis = MAJ[deg[v]%%7] + 12.f*(deg[v]/7) + 12.f*oct[v];
    float sh = (wheelJustify(semis)-semis)*100.f;
    if (fabsf(sh)>worst) worst=fabsf(sh);
    printf("    %%-11s degree %%d oct %%d -> %%5.1f st   TEMPER moves it %%+5.1f cents\n",
           nm[v], deg[v], oct[v], semis, sh);
  }
  printf("\n  largest shift anywhere in this voicing: %%.1f cents\n", worst);
  printf("  (roots, octaves and fifths barely move -- equal temperament already\n"
         "   gets those nearly right. TEMPER bites on THIRDS and SIXTHS.)\n");
}

static void run5(int nc, float crank){
  const float dt=1.f/48000.f;
  printf("what each stroke of a %%d-coup turn is worth, at %%.2f rev/s\n\n", nc, crank);
  printf("  slot  accent  strength   DOG that still fires it\n");
  for(int k=0;k<nc;k++){
    float a=wheelAccent(k,nc);
    float st=a*(0.85f+0.15f*clamp(crank*0.5f,0.f,2.f));
    printf("  %%3d   %%5.2f   %%6.3f   ", k, a, st);
    // invert the threshold line the engine uses, by search
    float best=-1.f;
    for(int d=100;d>=0;d--){ Rig r; r.dogK=d/100.f; r.speedBase=crank; r.speed=crank;
      r.coups=nc; int hit=0;
      for(int i=0;i<(int)(48000*20);i++){ r.speedBase=crank; r.nfire=0; r.step(dt);
        for(int q=0;q<r.nfire;q++) if(r.fireSlot[q]==k) hit++; }
      if(hit>0){ best=d/100.f; break; } }
    if(best<0) printf("never\n"); else printf("<= %%.2f\n", best);
  }
  printf("\n  the ladder has to be smooth, or DOG jumps from one group to the next\n");
}

static void run1(int NC){
  printf("stroke firing: which slots of a %%d-stroke turn buzz\n", NC);
  printf("accents      :");
  for(int k=0;k<NC;k++) printf(" %%.2f", wheelAccent(k,NC));
  printf("\n");
  // Coup slots and the seam are BOTH fixed to the wheel, so a given slot always
  // lands at the same point of the ripple -- the loss is systematic, not random.
  { Rig rr;
    printf("ripple at slot (RIPPLE=1):");
    for(int k=0;k<NC;k++){
      float g=1.f+1.f*rr.rippleAt((double)k/NC)*1.15f; if(g<1e-4f) g=1e-4f;
      printf(" %%+.0fdB", 20*log10f(g)); }
    printf("\n\n"); }
  const float dt = 1.f/48000.f;
  printf("        CRANK  0.5    1.0    1.6    3.0    6.0   rev/s\n");
  for (int d=0; d<=10; d++){
    float dog = d/10.f;
    printf("DOG %%4.2f      ", dog);
    for (float crank : {0.5f,1.0f,1.6f,3.0f,6.0f}){
      Rig r; r.dogK=dog; r.speedBase=crank; r.speed=crank; r.coups=NC;
      int hits[8]={0,0,0,0,0,0,0,0}; int turns=0;
      for (int i=0;i<(int)(48000*12);i++){
        r.speedBase=crank; r.nfire=0;
        double before=r.wheelPhase;
        r.step(dt);
        if (r.wheelPhase<before) turns++;
        for(int k=0;k<r.nfire;k++) hits[r.fireSlot[k]&7]++;
      }
      // density, not a majority: with the stroke jitter each slot fires a
      // FRACTION of the turns, and that fraction is the thing DOG sweeps.
      char b[9];
      for(int k=0;k<r.coups;k++){
        float f = turns ? (float)hits[k]/turns : 0.f;
        b[k] = f<0.02f ? '.' : f>0.98f ? '#' : ('0'+(int)(f*9.99f));
      }
      b[r.coups]=0;
      printf("%%-7s", b);
    }
    printf("\n");
  }
  printf("\n  # = fires every turn, 1-9 = fires that fraction of turns, . = silent\n");
}

static void run4(){
  const float dt=1.f/48000.f;
  printf("the press contour, against the exponential it replaces\n\n");
  for (float dur : {0.008f, 0.045f, 0.200f}) {
    WheelPress p; p.aim(1.f, dur, true);
    // the one-pole this used to be, at the same nominal time
    float e=0.f, eRate=1.f/dur;
    int n=(int)(dur*4.f/dt);
    float peak=0.f; int peakAt=0; int t90=-1, e90=-1;
    printf("  press time %%.0f ms\n", dur*1000.f);
    for(int i=0;i<n;i++){
      float v=p.process(dt); e += (1.f-e)*dt*eRate;
      if(v>peak){peak=v;peakAt=i;}
      if(t90<0 && v>=0.9f) t90=i;
      if(e90<0 && e>=0.9f) e90=i;
    }
    printf("    min-jerk : 90%%%% at %%5.1f ms, peak %%.3f at %%5.1f ms (overshoot %%+.1f%%%%)\n",
           t90*dt*1000.f, peak, peakAt*dt*1000.f, (peak-1.f)*100.f);
    printf("    one-pole : 90%%%% at %%5.1f ms, no overshoot, starts at full speed\n",
           e90*dt*1000.f);
    // velocity at the very first sample -- the thing a hand cannot do
    WheelPress q; q.aim(1.f, dur, true);
    float v0=q.process(dt), v1=q.process(dt);
    printf("    opening velocity: min-jerk %%.4f /sample vs one-pole %%.4f /sample\n\n",
           v1-v0, (1.f-0.f)*dt*eRate);
  }
  printf("  a hand has mass: it cannot start at full speed, and it cannot stop dead.\n");
}

static void run3(){
  Rig r;
  printf("what RIPPLE actually does, per setting\n");
  printf("  level  <- %%s\n  bright <- %%s\n\n", "%(ampFs)s", "%(brightFs)s");
  printf("  RIPPLE   level swing        brightness swing\n");
  for(int i=0;i<=10;i++){
    float depth=i/10.f;
    float alo=1e9f,ahi=-1e9f,blo=1e9f,bhi=-1e9f;
    for(int k=0;k<2048;k++){
      float rr=r.rippleAt(k/2048.0);
      float a=%(ampF)s; float b=%(brightF)s;
      if(a<alo)alo=a; if(a>ahi)ahi=a; if(b<blo)blo=b; if(b>bhi)bhi=b;
    }
    printf("  %%5.2f   %%+6.1f .. %%+5.1f dB   %%+6.1f .. %%+5.1f dB\n", depth,
           20*log10f(alo<1e-4f?1e-4f:alo), 20*log10f(ahi),
           20*log10f(blo<1e-4f?1e-4f:blo), 20*log10f(bhi));
  }
  printf("\n  a sustained drone needs several dB before a wobble is a wobble;\n"
         "  the first version topped out at 3.5 dB of level and 1.5 dB at default.\n");
}

static void run2(){
  Rig r;
  printf("ripple profile over one revolution (256 points)\n");
  float mn=1e9f,mx=-1e9f; int mnAt=0;
  for(int i=0;i<256;i++){ float v=r.rippleAt(i/256.0);
    if(v<mn){mn=v;mnAt=i;} if(v>mx)mx=v; }
  printf("  min %%+.3f at phase %%.3f   max %%+.3f   p-p %%.3f   (seam at %%.2f)\n",
         mn, mnAt/256.f, mx, mx-mn, WH_SEAM);
  float sum=0; for(int i=0;i<4096;i++) sum+=r.rippleAt(i/4096.0);
  printf("  mean %%+.4f  (a ripple with a DC offset is a level change, not a ripple)\n",
         sum/4096.f);
  for(int row=3;row>=-4;row--){
    printf("  %%+4.1f |", row*0.5f);
    for(int i=0;i<96;i++){ float v=r.rippleAt(i/96.0);
      printf("%%c", (v>=row*0.5f-0.25f && v<row*0.5f+0.25f)?'#':' '); }
    printf("\n");
  }
  printf("       +"); for(int i=0;i<96;i++) printf("-"); printf("\n");
  printf("        0                                                         phase 1\n");
}

int main(int c, char** v){
  int which = c>1 ? atoi(v[1]) : 1;
  if (which==6) { run6(); return 0; }
  if (which==5) { run5(c>2?atoi(v[2]):8, c>3?(float)atof(v[3]):1.28f); return 0; }
  if (which==4) run4(); else if (which==3) run3(); else if (which==2) run2(); else run1(c>2?atoi(v[2]):4);
  return 0;
}
''' % dict(seam=seam, maxc=maxc, justtab=justtab, justfn=justfn, gcdfn=gcdfn, accent=accent, ripple=ripple, crank=crank,
            ampF=ampF.replace(' r ', ' rr '), brightF=brightF.replace(' r,', ' rr,'),
            ampFs=ampF.replace('"',''), brightFs=brightF.replace('"',''),
            press=press.replace('random::uniform()', 'rnd::uniform()'))

# The engine records nothing about which stroke fired -- the harness needs that,
# so it is added at the one line where the dog fires, and nowhere else.
H = H.replace('\t\t\tdogFlash = 1.f;',
              '\t\t\tdogFlash = 1.f;\n\t\t\tif (nfire < 64) fireSlot[nfire++] = coupSlot;\n\t\t\tfires++;')
if 'fireSlot[nfire++]' not in H: sys.exit("EXTRACT FAILED: no dog-fire site to instrument")

H = H.replace('__FASTMATH__', os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'fastmath.hpp'))
open(os.path.join(OUT, 'h.cpp'), 'w').write(H)

# Build it HERE. The generator used to stop at writing h.cpp, and a compile
# failure then left the previous binary sitting there to be run and believed --
# which happened, and printed a four-stroke table for an eight-stroke question.
# A harness that can report a stale measurement is worse than no harness.
import subprocess
exe = os.path.join(OUT, 'h')
if os.path.exists(exe): os.remove(exe)
r = subprocess.run(['g++', '-std=c++11', '-O1', '-o', exe,
                    os.path.join(OUT, 'h.cpp')], capture_output=True, text=True)
if r.returncode != 0:
    sys.stderr.write(r.stderr)
    sys.exit("BUILD FAILED -- no binary written, so nothing stale can be run")
if sys.argv[1:]:
    sys.exit(subprocess.run([exe] + sys.argv[1:]).returncode)
print("built ./h -- pass args to this script to run it directly")
